### ISSUE TITLE
DalliError: Response error 6: Incr/decr on a non-numeric value

### ISSUE THREAD

**Issue by bjeanes** [yammer/circuitbox#128]
There is a comment in the code saying "yes we want a string here" but I don't understand how that behaviour is ever desirable. Furthermore, `incrementing` an empty value (at least in the handful of Moneta stores I tested) will create a value of `1` anyway.

https://github.com/yammer/circuitbox/blob/89aab2085dbf6f98ff7f8fc40a314103602f98da/lib/circuitbox/circuit_breaker.rb#L205-L214

In my case, I'm getting a string "1" getting through to Memcached, and then all further attempts to increment it are failing.

I've noticed that there is quite a departure between `master` and the last released version, so perhaps this is fixed, but I thought I'd open the issue anyway as there the most recently released stable version does seem to appear to have an odd issue here.

(This only cropped up after changing Moneta adapters but this was always backed by Memcache and since Circuitbox is _clearly_ sending a string intentionally I feel this bug belongs here)

**Comment by sideshowcoder** [comment]
As I'm the source of this comment, which I have to say was apparently not my brightest moment, here some explanation: 

Depending on the underlying store (!), if you sent anything other than a string, the value might be serialised, so you end up with a serialised ruby object instead of the thing you were looking for. A way to work around that is to use a type which is natively implemented (for example a String) in all stores. What is happening is that for the backends I worked with at the time, if you sent a string and later increment it it will "just work" aka the store increments the number, this is not true for all stores so as you point out. In essence yes you are right, if the store supports increment and numbers natively in the adapter (and depending on its implementation) this will not work. 

I can't comment on the fact if that is still the case in the master version, by using its own new fast storage this goes away. 

As a sidenote, the reason I did not test memcache at the time as it introduces a reliance on a central server (if shared memcache across multiple servers) or it means running memcache on each host which means I thought at the time would be better served by an alternative backend.

**Comment by bjeanes** [comment]
Thanks for the insight!

Is there any resolution you see other than upgrading to the pre-release version? I have a branch trying this but there are quite a lot of changes in semantics and API.

**Comment by matthewshafer** [comment]
This was fixed with #86, more specifically this commit c54b4be5c9136be71048507a872dcfa05a9d8df0. The 2.0.0.pre1 release contains the fix, but it's a pre release so I totally understand not wanting to run it. I don't know how easily cherry-picking the commit onto your branch of 1.x would be (I've made significant changes to circuitbox in that time).

I'll take this time to mention that with circuitbox 2.x moneta support is going to be deprecated (it can still be used but it's not the default storage engine). I talked a little about it in #113 in regards to the memory store.

**Comment by bjeanes** [comment]
Yeah I suppose I could drop Moneta but in particular use-case I actually want the shared circuit-breaker across services. I have a out-of-process indexer to ElasticSearch and I want that indexing and user-facing searches to trip the same circuit when ES becomes unavailable. I suppose using in-memory and allowing them all to trip would work, but seems harder to debug if some processes have tripped before others...

I am trying to get v2 working, but running into lots of issues that would probably be useful in an eventual upgrade guide:

* `Circuitbox.reset` is gone, which I use in my tests to make sure circuit state doesn't bleed across tests which test units using circuits. I'm doing this for now, but am not happy reaching into internals:

   ``` ruby
   Circuitbox.instance_variable_get(:@cached_circuits).each_value do |circuit|
     store = circuit.circuit_store
     store.delete(circuit.send :stat_storage_key, 'success')
     store.delete(circuit.send :stat_storage_key, 'failure')
     store.delete(circuit.send :open_storage_key)
     store.delete(circuit.send :half_open_storage_key)
   end
   ```
* I was using `timeout_seconds` option. I actually fully agree with the removal of this, but nonetheless having to work around this has been tricky.
* I'm seeing weird issues where my cached CircuitBreaker disappears, even though I haven't re-configured. I create the circuit in question during application initialization right after configuring Circuitbox:

   ``` ruby
   Circuitbox.configure do |config|
     config.default_circuit_store =
       Moneta.new(:ActiveSupportCache).
       prefix("circuitbox:#{Config.code_version[:commit]}:")
     config.default_logger = Rails.logger
   end

   Circuitbox.circuit(:es,
     exceptions: Search::IndexQueue::SERVER_DOWN_EXCEPTIONS,
     # ...
   )
   ```

   and yet, I am seeing this exception:

   ```
   KeyError:
     | key not found: :exceptions
   ```

   This strongly implies that cached circuits are being cleared but from a quick scan of the code, this appears only to happen if the circuit is re-configured.

   Nonetheless, I've observed the advise to not rely on the cache for fetching circuits and instead always invoke them fully configured. In this case, I'd think Circuitbox simply should not expose an API that allows fetching the circuit from a cache without providing all necessary options.
* `run!` -> `run`

**Comment by matthewshafer** [comment]
Thanks for the details on the experience with upgrading to 2.0. I'll put together an upgrade guide before 2.0.0 is released.

> Circuitbox.reset is gone, which I use in my tests to make sure circuit state doesn't bleed across tests which test units using circuits.

There are some details as to why ```Circuitbox.reset``` was removed in this commit 53fb72c904b98c78d609a697e22d8fbdc3a4e47f. ```Circuitbox.configure``` can be used to clear any cached circuits so in our test suite we combine that with setting a new in-memory store . This won't work for external circuit stores, but it didn't work for ```Circuitbox.reset``` either.

> I'm seeing weird issues where my cached CircuitBreaker disappears, even though I haven't re-configured.

If you have a way to reliably reproduce the cached circuits disappearing without running ```Circuitbox.configure```  please let us know. I spent some time last night trying to reproduce this but was unable to.

> I'd think Circuitbox simply should not expose an API that allows fetching the circuit from a cache without providing all necessary options.

Thanks for the feedback! We'll take this into consideration when we make changes to the Circuitbox api.

**Comment by bjeanes** [comment]
> If you have a way to reliably reproduce the cached circuits disappearing without running `Circuitbox.configure` please let us know. I spent some time last night trying to reproduce this but was unable to.

A test suite of mine consistently failed and the only place we run configure is in the initializer, but I can't rule out Rails' dev/test mode somehow re-running initializers. I've since refactored it to always invoke circuits fully configured, just in case /shrug

**Comment by bjeanes** [comment]
I'm going to close this. It doesn't seem worth solving for the v1 branch and is resolved in v2 whether or not an external store is used.

Thanks for working through this with me. I'm now on v2 pre-release.
