### ISSUE TITLE
Storage options

### ISSUE THREAD

**Issue by nickcampbell18** [yammer/circuitbox#38]
I noticed that we support both `ActiveSupport::Cache::MemoryStore` and a `Memcache` store - did we consider [PStore](https://robm.me.uk/ruby/2014/01/25/pstore.html)?

I'm using Circuitbox in a lightweight Ruby service but where I might want to use statistics across multiple processes, and using `memcached` just for this feels a little heavy handed.

**Comment by elg0nz** [comment]
@nickcampbell18 one caveat is that the Storage engine must support ["expirable" keys]( https://github.com/yammer/circuitbox/blob/master/lib/circuitbox/memcache_store.rb#L18)

Redis, Memcache, and [ActiveSupport](http://guides.rubyonrails.org/caching_with_rails.html#cache-stores) support this, while Pstore doesn't.

**Comment by sideshowcoder** [comment]
You might want to follow up on https://github.com/yammer/circuitbox/pull/34 this would allow us to use all kind of storage backends, but I would probably recommend again PStore as it has quite a high impact due to file locking and unlocking when re-read as a PStore can only ever be read in its entirety, not in parts.

**Comment by nickcampbell18** [comment]
Yes, closing this in favour of #34.
